services:
  app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    depends_on:
      - mysql
    networks:
      - mynetwork

  # mysql:
  #   image: mysql:8
  #   restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: root
  #     MYSQL_DATABASE: jira_clone
  #     MYSQL_USER: user
  #     MYSQL_PASSWORD: root
  #   ports:
  #     - "3307:3306"
  #   networks:
  #     - mynetwork
  #   command: --default-authentication-plugin=mysql_native_password

networks:
  mynetwork:
